name: Build Extension

on:
  release:
    types: [edited, created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - run: |
         cd app && npm install && npm run build
         mkdir -p build
    - run: |
        npm_package_version=$(jq -r '.version' app/package.json)
        jq ".version = \"${npm_package_version}\"" manifest.json > build/manifest.json
        cp -r images app/background.js app/content-script.js app/override.js README.md build
        cp app/node_modules/pako/dist/pako.min.js build/assets
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: 'build'
        filename: 'latest.zip'
    - name: Upload release
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            latest.zip
        tag_name: ${{  github.ref_name }}
        release_name: ${{  github.ref_name }}
        draft: false
        prerelease: false
        overwrite: true   
